<?php

namespace FrontendBundle\Repository;

use Doctrine\ORM\EntityManagerInterface;
use Doctrine\Common\Persistence\ManagerRegistry;
use Doctrine\DBAL\DriverManager;


/**
 * CoursIndependantRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CoursIndependantRepository extends \Doctrine\ORM\EntityRepository
{
    public function insertCours($cours,$em){
        $em->persist($cours);
        $em->flush();

        return $cours;
    }

    public function getId($cours,$em){
        $repository = $em->getRepository('FrontendBundle:CoursIndependant');
        $cours_temp = $repository->findby(array('datecreation' => $cours->getDatecreation(),'debut' => $cours->getDebut()));

        return $cours_temp;
    }

    public function getCours($id,$em){
        $repository = $em->getRepository('FrontendBundle:CoursIndependant');
        $cours_temp = $repository->findby(array('moduleIndependant' => $id));

        return $cours_temp;
    }

    public function getCoursFirst($id,$em){
        $repository = $em->getRepository('FrontendBundle:CoursIndependant');
        $cours_temp = $repository->findOneby(array('moduleIndependant' => $id));

        return $cours_temp;
    }

    public function getCoursDateDebutFirst($date,$em){
        $repository = $em->getRepository('FrontendBundle:CoursIndependant');
        $cours_temp = $repository->findOneby(array('debut' => $date));

        return $cours_temp;
    }

    public function getCoursDateFinFirst($date,$em){
        $repository = $em->getRepository('FrontendBundle:CoursIndependant');
        $cours_temp = $repository->findOneby(array('fin' => $date));

        return $cours_temp;
    }

    public function getCoursDateTest1($deb,$fin,$em){
        $sql = "SELECT c.idCours 
                FROM FrontendBundle:CoursIndependant c  
                WHERE c.debut <= '".$deb."' AND c.fin >='".$fin."'";

        $query = $em->createQuery($sql);

        return $query->getResult();
    }

    public function getCoursDateTest2($deb,$fin,$em){
        $sql = "SELECT c.idCours 
                FROM FrontendBundle:CoursIndependant c  
                WHERE c.fin >= '".$deb."' AND c.fin <='".$fin."'";

        $query = $em->createQuery($sql);

        return $query->getResult();
    }

    public function getCoursDateTest3($deb,$fin,$em){
        $sql = "SELECT c.idCours 
                FROM FrontendBundle:CoursIndependant c  
                WHERE c.debut >= '".$deb."' AND c.debut <='".$fin."'";

        $query = $em->createQuery($sql);

        return $query->getResult();
    }

    public function removeCours($cours,$em){
        $em->remove($cours);
        $em->flush();

        return $cours;
    }

    public function getCoursbyId($cours,$em){
        $repository = $em->getRepository('FrontendBundle:CoursIndependant');
        $cours_temp = $repository->find($cours);

        return $cours_temp;
    }
}
