<?php

namespace FrontendBundle\Repository;

use Doctrine\ORM\EntityManagerInterface;
use Doctrine\Common\Persistence\ManagerRegistry;
use Doctrine\DBAL\DriverManager;


/**
 * CoursIndependantRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CoursIndependantRepository extends \Doctrine\ORM\EntityRepository
{
    public function insertCours($cours,$em){
        $em->persist($cours);
        $em->flush();

        return $cours;
    }

    public function getId($cours,$em){
        $repository = $em->getRepository('FrontendBundle:CoursIndependant');
        $cours_temp = $repository->findby(array('datecreation' => $cours->getDatecreation(),'debut' => $cours->getDebut()));

        return $cours_temp;
    }

    public function getCours($id,$em){
        $repository = $em->getRepository('FrontendBundle:CoursIndependant');
        $cours_temp = $repository->findby(array('moduleIndependant' => $id));

        return $cours_temp;
    }

    public function removeCours($cours,$em){
        $em->remove($cours);
        $em->flush();

        return $cours;
    }

    public function getCoursbyId($cours,$em){
        $repository = $em->getRepository('FrontendBundle:CoursIndependant');
        $cours_temp = $repository->find($cours);

        return $cours_temp;
    }
}
