<?php

namespace FrontendBundle\Repository;

use Doctrine\ORM\EntityManagerInterface;
use Doctrine\Common\Persistence\ManagerRegistry;
use Doctrine\DBAL\DriverManager;


/**
 * ModuleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ModuleRepository extends \Doctrine\ORM\EntityRepository
{
    public function insertModule($module,$em){
        $em->persist($module);
        $em->flush();

        return $module;
    }

    public function getModules($em){
        $repository = $em->getRepository('FrontendBundle:ModuleIndependant');
        $module_temp = $repository->findAll();

        return $module_temp;
    }

    public function updateModule($module,$em){
        $em->persist($module);
        $em->flush();

        return $module;
    }

    public function removeModule($module,$em){
        $em->remove($module);
        $em->flush();

        return $module;
    }

    public function getModulebyId($module,$em){
        $repository = $em->getRepository('FrontendBundle:ModuleIndependant');
        $module_temp = $repository->find($module);

        return $module_temp;
    }
}
