<?php

namespace FrontendBundle\Repository;

use Doctrine\ORM\EntityManagerInterface;
use Doctrine\Common\Persistence\ManagerRegistry;
use Doctrine\DBAL\DriverManager;


/**
 * ParametreRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ParametreRepository extends \Doctrine\ORM\EntityRepository
{

    public function updateParametre($parametre,$em){
        $em->persist($parametre);
        $em->flush();

        return $parametre;
    }

    public function getParametre($libelle,$em){
        $repository = $em->getRepository('FrontendBundle:Parametre');
        $parametre_temp = $repository->findBy(array("libelle" => $libelle));

        return $parametre_temp;
    }


}
