<?php

namespace FrontendBundle\Repository;

use Doctrine\ORM\EntityManagerInterface;
use Doctrine\Common\Persistence\ManagerRegistry;
use Doctrine\DBAL\DriverManager;

/**
 * PlanningRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PlanningRepository extends \Doctrine\ORM\EntityRepository {

    public function getPlanningFormation($numlien, $em) {
        $sql = 'SELECT p.formationCode 
                FROM FrontendBundle:Planning p
                WHERE p.stagiaireEntrepriseNumlien = ' . $numlien;

        $query = $em->createQuery($sql);

        return $query->getResult();
    }

    public function getPlanningStagiaires($formation, $em) {
        $sql = "SELECT p.stagiaireEntrepriseNumlien 
                FROM FrontendBundle:Planning p
                WHERE p.formationCode = '" . $formation . "'";

        $query = $em->createQuery($sql);

        return $query->getResult();
    }

    public function getPlanningFormationDetail($numlien, $em) {
        $sql = 'SELECT p.dateDebut, p.dateFin, p.formationCode, p.etat 
                FROM FrontendBundle:Planning p
                WHERE p.stagiaireEntrepriseNumlien = ' . $numlien;

        $query = $em->createQuery($sql);

        return $query->getResult();
    }
    
    public function insertPlanning($planning, $em) {
        $em->persist($planning);
        $em->flush();

        return $planning;
    }

}
