<?php

namespace FrontendBundle\Repository;

use Doctrine\ORM\EntityManagerInterface;
use Doctrine\Common\Persistence\ManagerRegistry;
use Doctrine\DBAL\DriverManager;

/**
 * PlanningRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PlanningCoursRepository extends \Doctrine\ORM\EntityRepository {

    public function insertCours($cours, $em) {
        $em->persist($cours);
        $em->flush();

        return $cours;
    }

    public function getPlanningByCours($id,$em){
        $repository = $em->getRepository('FrontendBundle:PlanningCours');
        $cours_temp = $repository->findby(array('coursId' => $id));

        return $cours_temp;
    }

}
