<?php

namespace FrontendBundle\Repository;

use Doctrine\ORM\EntityManagerInterface;
use Doctrine\Common\Persistence\ManagerRegistry;
use Doctrine\DBAL\DriverManager;


/**
 * UtilisateurRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UtilisateurRepository extends \Doctrine\ORM\EntityRepository
{
	/**
	* Ajout d'un utilisateur
	*/
    public function insertUtilisateur($utilisateur,$em){
        $em->persist($utilisateur);
        $em->flush();

        return $utilisateur;
    }

	/**
	* Mise à jour d'un utilisateur
	*/
    public function updateUtilisateur($utilisateur,$em){
        $em->persist($utilisateur);
        $em->flush();

        return $utilisateur;
    }

	/**
	* Suppression d'un utilisateur
	*/
    public function removeUtilisateur($utilisateur,$em){
        $em->remove($utilisateur);
        $em->flush();

        return $utilisateur;
    }

	/**
	* Recuperation d'un utilisateur
	*/
    public function getUtilisateur($utilisateur,$em){
        $repository = $em->getRepository('FrontendBundle:Utilisateur');
        $utilisateur_temp = $repository->find($utilisateur);

        return $utilisateur_temp;
    }

	/**
	* Recuperation d'un utilisateur à partir de son mail
	*/
    public function getUtilisateurMail($mail,$em){
        $repository = $em->getRepository('FrontendBundle:Utilisateur');
        $utilisateur_temp = $repository->findBy(array("email" => $mail));

        return $utilisateur_temp;
}


}
