<?php

namespace FrontendBundle\Repository;

use Doctrine\ORM\EntityManagerInterface;
use Doctrine\Common\Persistence\ManagerRegistry;
use Doctrine\DBAL\DriverManager;


/**
 * UtilisateurRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UtilisateurRepository extends \Doctrine\ORM\EntityRepository
{
    public function insertUtilisateur($utilisateur,$em){
        $em->persist($utilisateur);
        $em->flush();

        return $utilisateur;
    }

    public function updateUtilisateur($utilisateur,$em){
        $em->persist($utilisateur);
        $em->flush();

        return $utilisateur;
    }

    public function removeUtilisateur($utilisateur,$em){
        $em->remove($utilisateur);
        $em->flush();

        return $utilisateur;
    }

    public function getUtilisateur($utilisateur,$em){
        $repository = $em->getRepository('FrontendBundle:Utilisateur');
        $utilisateur_temp = $repository->find($utilisateur);

        return $utilisateur_temp;
    }


}
