imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }
    - { resource: "@FrontendBundle/Resources/config/services.yml" }
    - { resource: "@EniBundle/Resources/config/services.yml" }

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: en

framework:
    #esi: ~
    #translator: { fallbacks: ['%locale%'] }
    secret: '%secret%'
    router:
        resource: '%kernel.project_dir%/app/config/routing.yml'
        strict_requirements: ~
    form: ~
    csrf_protection: ~
    validation: { enable_annotations: true }
    #serializer: { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale: '%locale%'
    trusted_hosts: ~
    session:
        # http://symfony.com/doc/current/reference/configuration/framework.html#handler-id
        handler_id: session.handler.native_file
        save_path: '%kernel.project_dir%/var/sessions/%kernel.environment%'
    fragments: ~
    http_method_override: true
    assets: ~
    php_errors:
        log: true

# Twig Configuration
twig:
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'

# Doctrine Configuration
doctrine:
    dbal:
        default_connection: groupeo
        connections:
              groupeo:
                    driver: pdo_sqlsrv
                    host: localhost\SQLEXPRESS
                    port: 1433
                    dbname: GroupeO
                    user: sa
                    password: Pa$$w0rd
                    charset: UTF8
              eni:
                    driver: pdo_sqlsrv
                    host: localhost\SQLEXPRESS
                    port: 1433
                    dbname: ENI_db
                    user: sa
                    password: Pa$$w0rd
                    charset: UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: "%kernel.project_dir%/var/data/data.sqlite"
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #path: '%database_path%'

    #orm:
    #    auto_generate_proxy_classes: '%kernel.debug%'
    #    naming_strategy: doctrine.orm.naming_strategy.underscore
    #    auto_mapping: true
    orm:
            default_entity_manager: groupeo
            auto_generate_proxy_classes: "%kernel.debug%"
            entity_managers:
                auto_mapping: true
                groupeo:
                    naming_strategy: doctrine.orm.naming_strategy.underscore
                    connection: groupeo
                    mappings:
                        FrontendBundle: ~
                eni:
                    naming_strategy: doctrine.orm.naming_strategy.underscore
                    connection: eni
                    mappings:
                        EniBundle: ~



# Swiftmailer Configuration
swiftmailer:
    transport: '%mailer_transport%'
    host: '%mailer_host%'
    username: '%mailer_user%'
    password: '%mailer_password%'
    spool: { type: memory }
