FrontendBundle\Entity\Planning:
    type: entity
    repositoryClass: FrontendBundle\Repository\PlanningRepository
    table: PLANNING
    indexes:
        IDX_12AA23BA73A201E5:
            columns:
                - createur_id
    id:
        idPlanning:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: id_planning
            generator:
                strategy: IDENTITY
    fields:
        nom:
            type: string
            nullable: false
            length: 50
            options:
                fixed: false
        dateCreation:
            type: date
            nullable: false
            column: date_creation
        dateDebut:
            type: date
            nullable: false
            column: date_debut
        dateFin:
            type: date
            nullable: false
            column: date_fin
        maxHeureFormation:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: max_heure_formation
        maxTempsFormation:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: max_temps_formation
        stagiaireEntrepriseNumlien:
            type: integer
            nullable: false
            options:
                unsigned: false
            column: stagiaire_entreprise_numlien
        stagiaireCode:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: stagiaire_code
        entrepriseCode:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: entreprise_code
        formationCode:
            type: integer
            nullable: false
            options:
                unsigned: false
            column: formation_code
    manyToOne:
        createur:
            targetEntity: Utilisateur
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                createur_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
