#ALTERNANT
alternant_recherche:
    path:     /alternant/recherche
    defaults: { _controller: EniBundle:Alternant:recherche }
alternant_chargement:
    path:     /alternant/chargement
    defaults: { _controller: EniBundle:Alternant:chargement }
recherche_alternant_planning:
    path:     /alternant/recherchePlanning
    defaults: { _controller: EniBundle:Alternant:recherchePlanning }
    methods: [post]
alternant_detail:
    path:     /alternant/detail/{id}
    defaults: { _controller: EniBundle:Alternant:detail }
    methods:  [GET]
user_alternant_recherche:
    path:     /recherche
    defaults: { _controller: EniBundle:Alternant:user_recherche }
user_alternant_detail:
    path:     /detail/{id}
    defaults: { _controller: EniBundle:Alternant:user_detail }
#ALTERNANT

#ENTREPRISE
entreprise_liste:
    path:     /entreprise/liste
    defaults: { _controller: EniBundle:Entreprise:liste }
    methods: [post]
#ENTREPRISE

#FORMATION
formation_liste:
    path:     /formation/liste
    defaults: { _controller: EniBundle:Formation:liste }
    methods: [post]
#FORMATION

#COURS
recherche :
    path:     /cours/recherche
    defaults: { _controller: EniBundle:Cours:recherche }
liste_cours_planning :
    path:     /cours/liste_cours_planning
    defaults: { _controller: EniBundle:Cours:listePlanning }
#COURS

#MODULE
frame_search :
    path :     /module/frameSearch
    defaults : {_controller : EniBundle:Module:frameSearch}
    methods: [post]
liste_search :
    path :     /module/listeSearch
    defaults : {_controller : EniBundle:Module:listeSearch}
    methods: [post]
#MODULE

