#ALTERNANT
alternant_recherche:
    path:     /alternant/recherche
    defaults: { _controller: EniBundle:Alternant:recherche }
alternant_chargement:
    path:     /alternant/chargement
    defaults: { _controller: EniBundle:Alternant:chargement }
recherche_alternant_planning:
    path:     /alternant/recherchePlanning
    defaults: { _controller: EniBundle:Alternant:recherchePlanning }
    methods: [post]
alternant_detail:
    path:     /alternant/detail/{id}
    defaults: { _controller: EniBundle:Alternant:detail }
    methods:  [GET]
#ALTERNANT

#ENTREPRISE
entreprise_liste:
    path:     /entreprise/liste
    defaults: { _controller: EniBundle:Entreprise:liste }
    methods: [post]
#ENTREPRISE

#FORMATION
formation_liste:
    path:     /formation/liste
    defaults: { _controller: EniBundle:Formation:liste }
    methods: [post]
#FORMATION