<?php

namespace Proxies\__CG__\EniBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Cours extends \EniBundle\Entity\Cours implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'EniBundle\\Entity\\Cours' . "\0" . 'debut', '' . "\0" . 'EniBundle\\Entity\\Cours' . "\0" . 'fin', '' . "\0" . 'EniBundle\\Entity\\Cours' . "\0" . 'dureereelleenheures', '' . "\0" . 'EniBundle\\Entity\\Cours' . "\0" . 'prixpublicaffecte', '' . "\0" . 'EniBundle\\Entity\\Cours' . "\0" . 'datecreation', '' . "\0" . 'EniBundle\\Entity\\Cours' . "\0" . 'libellecours', '' . "\0" . 'EniBundle\\Entity\\Cours' . "\0" . 'dureeprevueenheures', '' . "\0" . 'EniBundle\\Entity\\Cours' . "\0" . 'dateadefinir', '' . "\0" . 'EniBundle\\Entity\\Cours' . "\0" . 'codesalle', '' . "\0" . 'EniBundle\\Entity\\Cours' . "\0" . 'codeformateur', '' . "\0" . 'EniBundle\\Entity\\Cours' . "\0" . 'codelieu', '' . "\0" . 'EniBundle\\Entity\\Cours' . "\0" . 'idcours', '' . "\0" . 'EniBundle\\Entity\\Cours' . "\0" . 'idmodule', '' . "\0" . 'EniBundle\\Entity\\Cours' . "\0" . 'codepromotion'];
        }

        return ['__isInitialized__', '' . "\0" . 'EniBundle\\Entity\\Cours' . "\0" . 'debut', '' . "\0" . 'EniBundle\\Entity\\Cours' . "\0" . 'fin', '' . "\0" . 'EniBundle\\Entity\\Cours' . "\0" . 'dureereelleenheures', '' . "\0" . 'EniBundle\\Entity\\Cours' . "\0" . 'prixpublicaffecte', '' . "\0" . 'EniBundle\\Entity\\Cours' . "\0" . 'datecreation', '' . "\0" . 'EniBundle\\Entity\\Cours' . "\0" . 'libellecours', '' . "\0" . 'EniBundle\\Entity\\Cours' . "\0" . 'dureeprevueenheures', '' . "\0" . 'EniBundle\\Entity\\Cours' . "\0" . 'dateadefinir', '' . "\0" . 'EniBundle\\Entity\\Cours' . "\0" . 'codesalle', '' . "\0" . 'EniBundle\\Entity\\Cours' . "\0" . 'codeformateur', '' . "\0" . 'EniBundle\\Entity\\Cours' . "\0" . 'codelieu', '' . "\0" . 'EniBundle\\Entity\\Cours' . "\0" . 'idcours', '' . "\0" . 'EniBundle\\Entity\\Cours' . "\0" . 'idmodule', '' . "\0" . 'EniBundle\\Entity\\Cours' . "\0" . 'codepromotion'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Cours $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function setDebut($debut)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDebut', [$debut]);

        return parent::setDebut($debut);
    }

    /**
     * {@inheritDoc}
     */
    public function getDebut()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDebut', []);

        return parent::getDebut();
    }

    /**
     * {@inheritDoc}
     */
    public function setFin($fin)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFin', [$fin]);

        return parent::setFin($fin);
    }

    /**
     * {@inheritDoc}
     */
    public function getFin()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFin', []);

        return parent::getFin();
    }

    /**
     * {@inheritDoc}
     */
    public function setDureereelleenheures($dureereelleenheures)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDureereelleenheures', [$dureereelleenheures]);

        return parent::setDureereelleenheures($dureereelleenheures);
    }

    /**
     * {@inheritDoc}
     */
    public function getDureereelleenheures()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDureereelleenheures', []);

        return parent::getDureereelleenheures();
    }

    /**
     * {@inheritDoc}
     */
    public function setPrixpublicaffecte($prixpublicaffecte)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPrixpublicaffecte', [$prixpublicaffecte]);

        return parent::setPrixpublicaffecte($prixpublicaffecte);
    }

    /**
     * {@inheritDoc}
     */
    public function getPrixpublicaffecte()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPrixpublicaffecte', []);

        return parent::getPrixpublicaffecte();
    }

    /**
     * {@inheritDoc}
     */
    public function setDatecreation($datecreation)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDatecreation', [$datecreation]);

        return parent::setDatecreation($datecreation);
    }

    /**
     * {@inheritDoc}
     */
    public function getDatecreation()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDatecreation', []);

        return parent::getDatecreation();
    }

    /**
     * {@inheritDoc}
     */
    public function setLibellecours($libellecours)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLibellecours', [$libellecours]);

        return parent::setLibellecours($libellecours);
    }

    /**
     * {@inheritDoc}
     */
    public function getLibellecours()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLibellecours', []);

        return parent::getLibellecours();
    }

    /**
     * {@inheritDoc}
     */
    public function setDureeprevueenheures($dureeprevueenheures)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDureeprevueenheures', [$dureeprevueenheures]);

        return parent::setDureeprevueenheures($dureeprevueenheures);
    }

    /**
     * {@inheritDoc}
     */
    public function getDureeprevueenheures()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDureeprevueenheures', []);

        return parent::getDureeprevueenheures();
    }

    /**
     * {@inheritDoc}
     */
    public function setDateadefinir($dateadefinir)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDateadefinir', [$dateadefinir]);

        return parent::setDateadefinir($dateadefinir);
    }

    /**
     * {@inheritDoc}
     */
    public function getDateadefinir()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDateadefinir', []);

        return parent::getDateadefinir();
    }

    /**
     * {@inheritDoc}
     */
    public function setCodesalle($codesalle)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCodesalle', [$codesalle]);

        return parent::setCodesalle($codesalle);
    }

    /**
     * {@inheritDoc}
     */
    public function getCodesalle()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCodesalle', []);

        return parent::getCodesalle();
    }

    /**
     * {@inheritDoc}
     */
    public function setCodeformateur($codeformateur)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCodeformateur', [$codeformateur]);

        return parent::setCodeformateur($codeformateur);
    }

    /**
     * {@inheritDoc}
     */
    public function getCodeformateur()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCodeformateur', []);

        return parent::getCodeformateur();
    }

    /**
     * {@inheritDoc}
     */
    public function setCodelieu($codelieu)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCodelieu', [$codelieu]);

        return parent::setCodelieu($codelieu);
    }

    /**
     * {@inheritDoc}
     */
    public function getCodelieu()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCodelieu', []);

        return parent::getCodelieu();
    }

    /**
     * {@inheritDoc}
     */
    public function getIdcours()
    {
        if ($this->__isInitialized__ === false) {
            return  parent::getIdcours();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdcours', []);

        return parent::getIdcours();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdmodule(\EniBundle\Entity\Module $idmodule = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdmodule', [$idmodule]);

        return parent::setIdmodule($idmodule);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdmodule()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdmodule', []);

        return parent::getIdmodule();
    }

    /**
     * {@inheritDoc}
     */
    public function setCodepromotion(\EniBundle\Entity\Promotion $codepromotion = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCodepromotion', [$codepromotion]);

        return parent::setCodepromotion($codepromotion);
    }

    /**
     * {@inheritDoc}
     */
    public function getCodepromotion()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCodepromotion', []);

        return parent::getCodepromotion();
    }

}
