<?php

namespace Proxies\__CG__\EniBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Uniteformation extends \EniBundle\Entity\Uniteformation implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'EniBundle\\Entity\\Uniteformation' . "\0" . 'libelle', '' . "\0" . 'EniBundle\\Entity\\Uniteformation' . "\0" . 'dureeenheures', '' . "\0" . 'EniBundle\\Entity\\Uniteformation' . "\0" . 'datecreation', '' . "\0" . 'EniBundle\\Entity\\Uniteformation' . "\0" . 'dureeensemaines', '' . "\0" . 'EniBundle\\Entity\\Uniteformation' . "\0" . 'libellecourt', '' . "\0" . 'EniBundle\\Entity\\Uniteformation' . "\0" . 'archiver', '' . "\0" . 'EniBundle\\Entity\\Uniteformation' . "\0" . 'iduniteformation'];
        }

        return ['__isInitialized__', '' . "\0" . 'EniBundle\\Entity\\Uniteformation' . "\0" . 'libelle', '' . "\0" . 'EniBundle\\Entity\\Uniteformation' . "\0" . 'dureeenheures', '' . "\0" . 'EniBundle\\Entity\\Uniteformation' . "\0" . 'datecreation', '' . "\0" . 'EniBundle\\Entity\\Uniteformation' . "\0" . 'dureeensemaines', '' . "\0" . 'EniBundle\\Entity\\Uniteformation' . "\0" . 'libellecourt', '' . "\0" . 'EniBundle\\Entity\\Uniteformation' . "\0" . 'archiver', '' . "\0" . 'EniBundle\\Entity\\Uniteformation' . "\0" . 'iduniteformation'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Uniteformation $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function setLibelle($libelle)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLibelle', [$libelle]);

        return parent::setLibelle($libelle);
    }

    /**
     * {@inheritDoc}
     */
    public function getLibelle()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLibelle', []);

        return parent::getLibelle();
    }

    /**
     * {@inheritDoc}
     */
    public function setDureeenheures($dureeenheures)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDureeenheures', [$dureeenheures]);

        return parent::setDureeenheures($dureeenheures);
    }

    /**
     * {@inheritDoc}
     */
    public function getDureeenheures()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDureeenheures', []);

        return parent::getDureeenheures();
    }

    /**
     * {@inheritDoc}
     */
    public function setDatecreation($datecreation)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDatecreation', [$datecreation]);

        return parent::setDatecreation($datecreation);
    }

    /**
     * {@inheritDoc}
     */
    public function getDatecreation()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDatecreation', []);

        return parent::getDatecreation();
    }

    /**
     * {@inheritDoc}
     */
    public function setDureeensemaines($dureeensemaines)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDureeensemaines', [$dureeensemaines]);

        return parent::setDureeensemaines($dureeensemaines);
    }

    /**
     * {@inheritDoc}
     */
    public function getDureeensemaines()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDureeensemaines', []);

        return parent::getDureeensemaines();
    }

    /**
     * {@inheritDoc}
     */
    public function setLibellecourt($libellecourt)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLibellecourt', [$libellecourt]);

        return parent::setLibellecourt($libellecourt);
    }

    /**
     * {@inheritDoc}
     */
    public function getLibellecourt()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLibellecourt', []);

        return parent::getLibellecourt();
    }

    /**
     * {@inheritDoc}
     */
    public function setArchiver($archiver)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setArchiver', [$archiver]);

        return parent::setArchiver($archiver);
    }

    /**
     * {@inheritDoc}
     */
    public function getArchiver()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getArchiver', []);

        return parent::getArchiver();
    }

    /**
     * {@inheritDoc}
     */
    public function getIduniteformation()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getIduniteformation();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIduniteformation', []);

        return parent::getIduniteformation();
    }

}
