<?php

namespace Proxies\__CG__\EniBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Promotion extends \EniBundle\Entity\Promotion implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'EniBundle\\Entity\\Promotion' . "\0" . 'libelle', '' . "\0" . 'EniBundle\\Entity\\Promotion' . "\0" . 'debut', '' . "\0" . 'EniBundle\\Entity\\Promotion' . "\0" . 'fin', '' . "\0" . 'EniBundle\\Entity\\Promotion' . "\0" . 'prixpublicaffecte', '' . "\0" . 'EniBundle\\Entity\\Promotion' . "\0" . 'datecreation', '' . "\0" . 'EniBundle\\Entity\\Promotion' . "\0" . 'prixpecaffecte', '' . "\0" . 'EniBundle\\Entity\\Promotion' . "\0" . 'prixfinanceaffecte', '' . "\0" . 'EniBundle\\Entity\\Promotion' . "\0" . 'codecontacteni', '' . "\0" . 'EniBundle\\Entity\\Promotion' . "\0" . 'codelieu', '' . "\0" . 'EniBundle\\Entity\\Promotion' . "\0" . 'codepromotion', '' . "\0" . 'EniBundle\\Entity\\Promotion' . "\0" . 'codeformation'];
        }

        return ['__isInitialized__', '' . "\0" . 'EniBundle\\Entity\\Promotion' . "\0" . 'libelle', '' . "\0" . 'EniBundle\\Entity\\Promotion' . "\0" . 'debut', '' . "\0" . 'EniBundle\\Entity\\Promotion' . "\0" . 'fin', '' . "\0" . 'EniBundle\\Entity\\Promotion' . "\0" . 'prixpublicaffecte', '' . "\0" . 'EniBundle\\Entity\\Promotion' . "\0" . 'datecreation', '' . "\0" . 'EniBundle\\Entity\\Promotion' . "\0" . 'prixpecaffecte', '' . "\0" . 'EniBundle\\Entity\\Promotion' . "\0" . 'prixfinanceaffecte', '' . "\0" . 'EniBundle\\Entity\\Promotion' . "\0" . 'codecontacteni', '' . "\0" . 'EniBundle\\Entity\\Promotion' . "\0" . 'codelieu', '' . "\0" . 'EniBundle\\Entity\\Promotion' . "\0" . 'codepromotion', '' . "\0" . 'EniBundle\\Entity\\Promotion' . "\0" . 'codeformation'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Promotion $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function setLibelle($libelle)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLibelle', [$libelle]);

        return parent::setLibelle($libelle);
    }

    /**
     * {@inheritDoc}
     */
    public function getLibelle()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLibelle', []);

        return parent::getLibelle();
    }

    /**
     * {@inheritDoc}
     */
    public function setDebut($debut)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDebut', [$debut]);

        return parent::setDebut($debut);
    }

    /**
     * {@inheritDoc}
     */
    public function getDebut()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDebut', []);

        return parent::getDebut();
    }

    /**
     * {@inheritDoc}
     */
    public function setFin($fin)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFin', [$fin]);

        return parent::setFin($fin);
    }

    /**
     * {@inheritDoc}
     */
    public function getFin()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFin', []);

        return parent::getFin();
    }

    /**
     * {@inheritDoc}
     */
    public function setPrixpublicaffecte($prixpublicaffecte)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPrixpublicaffecte', [$prixpublicaffecte]);

        return parent::setPrixpublicaffecte($prixpublicaffecte);
    }

    /**
     * {@inheritDoc}
     */
    public function getPrixpublicaffecte()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPrixpublicaffecte', []);

        return parent::getPrixpublicaffecte();
    }

    /**
     * {@inheritDoc}
     */
    public function setDatecreation($datecreation)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDatecreation', [$datecreation]);

        return parent::setDatecreation($datecreation);
    }

    /**
     * {@inheritDoc}
     */
    public function getDatecreation()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDatecreation', []);

        return parent::getDatecreation();
    }

    /**
     * {@inheritDoc}
     */
    public function setPrixpecaffecte($prixpecaffecte)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPrixpecaffecte', [$prixpecaffecte]);

        return parent::setPrixpecaffecte($prixpecaffecte);
    }

    /**
     * {@inheritDoc}
     */
    public function getPrixpecaffecte()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPrixpecaffecte', []);

        return parent::getPrixpecaffecte();
    }

    /**
     * {@inheritDoc}
     */
    public function setPrixfinanceaffecte($prixfinanceaffecte)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPrixfinanceaffecte', [$prixfinanceaffecte]);

        return parent::setPrixfinanceaffecte($prixfinanceaffecte);
    }

    /**
     * {@inheritDoc}
     */
    public function getPrixfinanceaffecte()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPrixfinanceaffecte', []);

        return parent::getPrixfinanceaffecte();
    }

    /**
     * {@inheritDoc}
     */
    public function setCodecontacteni($codecontacteni)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCodecontacteni', [$codecontacteni]);

        return parent::setCodecontacteni($codecontacteni);
    }

    /**
     * {@inheritDoc}
     */
    public function getCodecontacteni()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCodecontacteni', []);

        return parent::getCodecontacteni();
    }

    /**
     * {@inheritDoc}
     */
    public function setCodelieu($codelieu)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCodelieu', [$codelieu]);

        return parent::setCodelieu($codelieu);
    }

    /**
     * {@inheritDoc}
     */
    public function getCodelieu()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCodelieu', []);

        return parent::getCodelieu();
    }

    /**
     * {@inheritDoc}
     */
    public function getCodepromotion()
    {
        if ($this->__isInitialized__ === false) {
            return  parent::getCodepromotion();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCodepromotion', []);

        return parent::getCodepromotion();
    }

    /**
     * {@inheritDoc}
     */
    public function setCodeformation(\EniBundle\Entity\Formation $codeformation = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCodeformation', [$codeformation]);

        return parent::setCodeformation($codeformation);
    }

    /**
     * {@inheritDoc}
     */
    public function getCodeformation()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCodeformation', []);

        return parent::getCodeformation();
    }

}
