<?php

namespace Proxies\__CG__\EniBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Stagiaireparentreprise extends \EniBundle\Entity\Stagiaireparentreprise implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'EniBundle\\Entity\\Stagiaireparentreprise' . "\0" . 'codestagiaire', '' . "\0" . 'EniBundle\\Entity\\Stagiaireparentreprise' . "\0" . 'codeentreprise', '' . "\0" . 'EniBundle\\Entity\\Stagiaireparentreprise' . "\0" . 'datelien', '' . "\0" . 'EniBundle\\Entity\\Stagiaireparentreprise' . "\0" . 'codetypelien', '' . "\0" . 'EniBundle\\Entity\\Stagiaireparentreprise' . "\0" . 'datedebutenets', '' . "\0" . 'EniBundle\\Entity\\Stagiaireparentreprise' . "\0" . 'datefinenets', '' . "\0" . 'EniBundle\\Entity\\Stagiaireparentreprise' . "\0" . 'codefonction', '' . "\0" . 'EniBundle\\Entity\\Stagiaireparentreprise' . "\0" . 'commentaire', '' . "\0" . 'EniBundle\\Entity\\Stagiaireparentreprise' . "\0" . 'codetuteur', '' . "\0" . 'EniBundle\\Entity\\Stagiaireparentreprise' . "\0" . 'responsableets', '' . "\0" . 'EniBundle\\Entity\\Stagiaireparentreprise' . "\0" . 'gererpar', '' . "\0" . 'EniBundle\\Entity\\Stagiaireparentreprise' . "\0" . 'interruption', '' . "\0" . 'EniBundle\\Entity\\Stagiaireparentreprise' . "\0" . 'sujetstage', '' . "\0" . 'EniBundle\\Entity\\Stagiaireparentreprise' . "\0" . 'titrevise', '' . "\0" . 'EniBundle\\Entity\\Stagiaireparentreprise' . "\0" . 'codecontacteni', '' . "\0" . 'EniBundle\\Entity\\Stagiaireparentreprise' . "\0" . 'numlien'];
        }

        return ['__isInitialized__', '' . "\0" . 'EniBundle\\Entity\\Stagiaireparentreprise' . "\0" . 'codestagiaire', '' . "\0" . 'EniBundle\\Entity\\Stagiaireparentreprise' . "\0" . 'codeentreprise', '' . "\0" . 'EniBundle\\Entity\\Stagiaireparentreprise' . "\0" . 'datelien', '' . "\0" . 'EniBundle\\Entity\\Stagiaireparentreprise' . "\0" . 'codetypelien', '' . "\0" . 'EniBundle\\Entity\\Stagiaireparentreprise' . "\0" . 'datedebutenets', '' . "\0" . 'EniBundle\\Entity\\Stagiaireparentreprise' . "\0" . 'datefinenets', '' . "\0" . 'EniBundle\\Entity\\Stagiaireparentreprise' . "\0" . 'codefonction', '' . "\0" . 'EniBundle\\Entity\\Stagiaireparentreprise' . "\0" . 'commentaire', '' . "\0" . 'EniBundle\\Entity\\Stagiaireparentreprise' . "\0" . 'codetuteur', '' . "\0" . 'EniBundle\\Entity\\Stagiaireparentreprise' . "\0" . 'responsableets', '' . "\0" . 'EniBundle\\Entity\\Stagiaireparentreprise' . "\0" . 'gererpar', '' . "\0" . 'EniBundle\\Entity\\Stagiaireparentreprise' . "\0" . 'interruption', '' . "\0" . 'EniBundle\\Entity\\Stagiaireparentreprise' . "\0" . 'sujetstage', '' . "\0" . 'EniBundle\\Entity\\Stagiaireparentreprise' . "\0" . 'titrevise', '' . "\0" . 'EniBundle\\Entity\\Stagiaireparentreprise' . "\0" . 'codecontacteni', '' . "\0" . 'EniBundle\\Entity\\Stagiaireparentreprise' . "\0" . 'numlien'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Stagiaireparentreprise $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function setCodestagiaire($codestagiaire)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCodestagiaire', [$codestagiaire]);

        return parent::setCodestagiaire($codestagiaire);
    }

    /**
     * {@inheritDoc}
     */
    public function getCodestagiaire()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCodestagiaire', []);

        return parent::getCodestagiaire();
    }

    /**
     * {@inheritDoc}
     */
    public function setCodeentreprise($codeentreprise)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCodeentreprise', [$codeentreprise]);

        return parent::setCodeentreprise($codeentreprise);
    }

    /**
     * {@inheritDoc}
     */
    public function getCodeentreprise()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCodeentreprise', []);

        return parent::getCodeentreprise();
    }

    /**
     * {@inheritDoc}
     */
    public function setDatelien($datelien)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDatelien', [$datelien]);

        return parent::setDatelien($datelien);
    }

    /**
     * {@inheritDoc}
     */
    public function getDatelien()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDatelien', []);

        return parent::getDatelien();
    }

    /**
     * {@inheritDoc}
     */
    public function setCodetypelien($codetypelien)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCodetypelien', [$codetypelien]);

        return parent::setCodetypelien($codetypelien);
    }

    /**
     * {@inheritDoc}
     */
    public function getCodetypelien()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCodetypelien', []);

        return parent::getCodetypelien();
    }

    /**
     * {@inheritDoc}
     */
    public function setDatedebutenets($datedebutenets)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDatedebutenets', [$datedebutenets]);

        return parent::setDatedebutenets($datedebutenets);
    }

    /**
     * {@inheritDoc}
     */
    public function getDatedebutenets()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDatedebutenets', []);

        return parent::getDatedebutenets();
    }

    /**
     * {@inheritDoc}
     */
    public function setDatefinenets($datefinenets)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDatefinenets', [$datefinenets]);

        return parent::setDatefinenets($datefinenets);
    }

    /**
     * {@inheritDoc}
     */
    public function getDatefinenets()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDatefinenets', []);

        return parent::getDatefinenets();
    }

    /**
     * {@inheritDoc}
     */
    public function setCodefonction($codefonction)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCodefonction', [$codefonction]);

        return parent::setCodefonction($codefonction);
    }

    /**
     * {@inheritDoc}
     */
    public function getCodefonction()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCodefonction', []);

        return parent::getCodefonction();
    }

    /**
     * {@inheritDoc}
     */
    public function setCommentaire($commentaire)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCommentaire', [$commentaire]);

        return parent::setCommentaire($commentaire);
    }

    /**
     * {@inheritDoc}
     */
    public function getCommentaire()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCommentaire', []);

        return parent::getCommentaire();
    }

    /**
     * {@inheritDoc}
     */
    public function setCodetuteur($codetuteur)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCodetuteur', [$codetuteur]);

        return parent::setCodetuteur($codetuteur);
    }

    /**
     * {@inheritDoc}
     */
    public function getCodetuteur()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCodetuteur', []);

        return parent::getCodetuteur();
    }

    /**
     * {@inheritDoc}
     */
    public function setResponsableets($responsableets)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setResponsableets', [$responsableets]);

        return parent::setResponsableets($responsableets);
    }

    /**
     * {@inheritDoc}
     */
    public function getResponsableets()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getResponsableets', []);

        return parent::getResponsableets();
    }

    /**
     * {@inheritDoc}
     */
    public function setGererpar($gererpar)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setGererpar', [$gererpar]);

        return parent::setGererpar($gererpar);
    }

    /**
     * {@inheritDoc}
     */
    public function getGererpar()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getGererpar', []);

        return parent::getGererpar();
    }

    /**
     * {@inheritDoc}
     */
    public function setInterruption($interruption)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setInterruption', [$interruption]);

        return parent::setInterruption($interruption);
    }

    /**
     * {@inheritDoc}
     */
    public function getInterruption()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getInterruption', []);

        return parent::getInterruption();
    }

    /**
     * {@inheritDoc}
     */
    public function setSujetstage($sujetstage)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSujetstage', [$sujetstage]);

        return parent::setSujetstage($sujetstage);
    }

    /**
     * {@inheritDoc}
     */
    public function getSujetstage()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSujetstage', []);

        return parent::getSujetstage();
    }

    /**
     * {@inheritDoc}
     */
    public function setTitrevise($titrevise)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTitrevise', [$titrevise]);

        return parent::setTitrevise($titrevise);
    }

    /**
     * {@inheritDoc}
     */
    public function getTitrevise()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTitrevise', []);

        return parent::getTitrevise();
    }

    /**
     * {@inheritDoc}
     */
    public function setCodecontacteni($codecontacteni)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCodecontacteni', [$codecontacteni]);

        return parent::setCodecontacteni($codecontacteni);
    }

    /**
     * {@inheritDoc}
     */
    public function getCodecontacteni()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCodecontacteni', []);

        return parent::getCodecontacteni();
    }

    /**
     * {@inheritDoc}
     */
    public function getNumlien()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getNumlien();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNumlien', []);

        return parent::getNumlien();
    }

}
