<?php

namespace Proxies\__CG__\EniBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Formation extends \EniBundle\Entity\Formation implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'EniBundle\\Entity\\Formation' . "\0" . 'libellelong', '' . "\0" . 'EniBundle\\Entity\\Formation' . "\0" . 'libellecourt', '' . "\0" . 'EniBundle\\Entity\\Formation' . "\0" . 'dureeenheures', '' . "\0" . 'EniBundle\\Entity\\Formation' . "\0" . 'tauxhoraire', '' . "\0" . 'EniBundle\\Entity\\Formation' . "\0" . 'datecreation', '' . "\0" . 'EniBundle\\Entity\\Formation' . "\0" . 'codetitre', '' . "\0" . 'EniBundle\\Entity\\Formation' . "\0" . 'prixpublicencours', '' . "\0" . 'EniBundle\\Entity\\Formation' . "\0" . 'heurescentre', '' . "\0" . 'EniBundle\\Entity\\Formation' . "\0" . 'heuresstage', '' . "\0" . 'EniBundle\\Entity\\Formation' . "\0" . 'semainescentre', '' . "\0" . 'EniBundle\\Entity\\Formation' . "\0" . 'semainesstage', '' . "\0" . 'EniBundle\\Entity\\Formation' . "\0" . 'dureeensemaines', '' . "\0" . 'EniBundle\\Entity\\Formation' . "\0" . 'archiver', '' . "\0" . 'EniBundle\\Entity\\Formation' . "\0" . 'ecfapasser', '' . "\0" . 'EniBundle\\Entity\\Formation' . "\0" . 'typeformation', '' . "\0" . 'EniBundle\\Entity\\Formation' . "\0" . 'codelieu', '' . "\0" . 'EniBundle\\Entity\\Formation' . "\0" . 'codeformation'];
        }

        return ['__isInitialized__', '' . "\0" . 'EniBundle\\Entity\\Formation' . "\0" . 'libellelong', '' . "\0" . 'EniBundle\\Entity\\Formation' . "\0" . 'libellecourt', '' . "\0" . 'EniBundle\\Entity\\Formation' . "\0" . 'dureeenheures', '' . "\0" . 'EniBundle\\Entity\\Formation' . "\0" . 'tauxhoraire', '' . "\0" . 'EniBundle\\Entity\\Formation' . "\0" . 'datecreation', '' . "\0" . 'EniBundle\\Entity\\Formation' . "\0" . 'codetitre', '' . "\0" . 'EniBundle\\Entity\\Formation' . "\0" . 'prixpublicencours', '' . "\0" . 'EniBundle\\Entity\\Formation' . "\0" . 'heurescentre', '' . "\0" . 'EniBundle\\Entity\\Formation' . "\0" . 'heuresstage', '' . "\0" . 'EniBundle\\Entity\\Formation' . "\0" . 'semainescentre', '' . "\0" . 'EniBundle\\Entity\\Formation' . "\0" . 'semainesstage', '' . "\0" . 'EniBundle\\Entity\\Formation' . "\0" . 'dureeensemaines', '' . "\0" . 'EniBundle\\Entity\\Formation' . "\0" . 'archiver', '' . "\0" . 'EniBundle\\Entity\\Formation' . "\0" . 'ecfapasser', '' . "\0" . 'EniBundle\\Entity\\Formation' . "\0" . 'typeformation', '' . "\0" . 'EniBundle\\Entity\\Formation' . "\0" . 'codelieu', '' . "\0" . 'EniBundle\\Entity\\Formation' . "\0" . 'codeformation'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Formation $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function setLibellelong($libellelong)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLibellelong', [$libellelong]);

        return parent::setLibellelong($libellelong);
    }

    /**
     * {@inheritDoc}
     */
    public function getLibellelong()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLibellelong', []);

        return parent::getLibellelong();
    }

    /**
     * {@inheritDoc}
     */
    public function setLibellecourt($libellecourt)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLibellecourt', [$libellecourt]);

        return parent::setLibellecourt($libellecourt);
    }

    /**
     * {@inheritDoc}
     */
    public function getLibellecourt()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLibellecourt', []);

        return parent::getLibellecourt();
    }

    /**
     * {@inheritDoc}
     */
    public function setDureeenheures($dureeenheures)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDureeenheures', [$dureeenheures]);

        return parent::setDureeenheures($dureeenheures);
    }

    /**
     * {@inheritDoc}
     */
    public function getDureeenheures()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDureeenheures', []);

        return parent::getDureeenheures();
    }

    /**
     * {@inheritDoc}
     */
    public function setTauxhoraire($tauxhoraire)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTauxhoraire', [$tauxhoraire]);

        return parent::setTauxhoraire($tauxhoraire);
    }

    /**
     * {@inheritDoc}
     */
    public function getTauxhoraire()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTauxhoraire', []);

        return parent::getTauxhoraire();
    }

    /**
     * {@inheritDoc}
     */
    public function setDatecreation($datecreation)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDatecreation', [$datecreation]);

        return parent::setDatecreation($datecreation);
    }

    /**
     * {@inheritDoc}
     */
    public function getDatecreation()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDatecreation', []);

        return parent::getDatecreation();
    }

    /**
     * {@inheritDoc}
     */
    public function setCodetitre($codetitre)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCodetitre', [$codetitre]);

        return parent::setCodetitre($codetitre);
    }

    /**
     * {@inheritDoc}
     */
    public function getCodetitre()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCodetitre', []);

        return parent::getCodetitre();
    }

    /**
     * {@inheritDoc}
     */
    public function setPrixpublicencours($prixpublicencours)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPrixpublicencours', [$prixpublicencours]);

        return parent::setPrixpublicencours($prixpublicencours);
    }

    /**
     * {@inheritDoc}
     */
    public function getPrixpublicencours()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPrixpublicencours', []);

        return parent::getPrixpublicencours();
    }

    /**
     * {@inheritDoc}
     */
    public function setHeurescentre($heurescentre)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setHeurescentre', [$heurescentre]);

        return parent::setHeurescentre($heurescentre);
    }

    /**
     * {@inheritDoc}
     */
    public function getHeurescentre()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getHeurescentre', []);

        return parent::getHeurescentre();
    }

    /**
     * {@inheritDoc}
     */
    public function setHeuresstage($heuresstage)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setHeuresstage', [$heuresstage]);

        return parent::setHeuresstage($heuresstage);
    }

    /**
     * {@inheritDoc}
     */
    public function getHeuresstage()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getHeuresstage', []);

        return parent::getHeuresstage();
    }

    /**
     * {@inheritDoc}
     */
    public function setSemainescentre($semainescentre)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSemainescentre', [$semainescentre]);

        return parent::setSemainescentre($semainescentre);
    }

    /**
     * {@inheritDoc}
     */
    public function getSemainescentre()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSemainescentre', []);

        return parent::getSemainescentre();
    }

    /**
     * {@inheritDoc}
     */
    public function setSemainesstage($semainesstage)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSemainesstage', [$semainesstage]);

        return parent::setSemainesstage($semainesstage);
    }

    /**
     * {@inheritDoc}
     */
    public function getSemainesstage()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSemainesstage', []);

        return parent::getSemainesstage();
    }

    /**
     * {@inheritDoc}
     */
    public function setDureeensemaines($dureeensemaines)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDureeensemaines', [$dureeensemaines]);

        return parent::setDureeensemaines($dureeensemaines);
    }

    /**
     * {@inheritDoc}
     */
    public function getDureeensemaines()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDureeensemaines', []);

        return parent::getDureeensemaines();
    }

    /**
     * {@inheritDoc}
     */
    public function setArchiver($archiver)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setArchiver', [$archiver]);

        return parent::setArchiver($archiver);
    }

    /**
     * {@inheritDoc}
     */
    public function getArchiver()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getArchiver', []);

        return parent::getArchiver();
    }

    /**
     * {@inheritDoc}
     */
    public function setEcfapasser($ecfapasser)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEcfapasser', [$ecfapasser]);

        return parent::setEcfapasser($ecfapasser);
    }

    /**
     * {@inheritDoc}
     */
    public function getEcfapasser()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEcfapasser', []);

        return parent::getEcfapasser();
    }

    /**
     * {@inheritDoc}
     */
    public function setTypeformation($typeformation)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTypeformation', [$typeformation]);

        return parent::setTypeformation($typeformation);
    }

    /**
     * {@inheritDoc}
     */
    public function getTypeformation()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTypeformation', []);

        return parent::getTypeformation();
    }

    /**
     * {@inheritDoc}
     */
    public function setCodelieu($codelieu)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCodelieu', [$codelieu]);

        return parent::setCodelieu($codelieu);
    }

    /**
     * {@inheritDoc}
     */
    public function getCodelieu()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCodelieu', []);

        return parent::getCodelieu();
    }

    /**
     * {@inheritDoc}
     */
    public function getCodeformation()
    {
        if ($this->__isInitialized__ === false) {
            return  parent::getCodeformation();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCodeformation', []);

        return parent::getCodeformation();
    }

}
