<?php

namespace Proxies\__CG__\EniBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Stagiaire extends \EniBundle\Entity\Stagiaire implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'EniBundle\\Entity\\Stagiaire' . "\0" . 'civilite', '' . "\0" . 'EniBundle\\Entity\\Stagiaire' . "\0" . 'nom', '' . "\0" . 'EniBundle\\Entity\\Stagiaire' . "\0" . 'prenom', '' . "\0" . 'EniBundle\\Entity\\Stagiaire' . "\0" . 'adresse1', '' . "\0" . 'EniBundle\\Entity\\Stagiaire' . "\0" . 'adresse2', '' . "\0" . 'EniBundle\\Entity\\Stagiaire' . "\0" . 'adresse3', '' . "\0" . 'EniBundle\\Entity\\Stagiaire' . "\0" . 'codepostal', '' . "\0" . 'EniBundle\\Entity\\Stagiaire' . "\0" . 'ville', '' . "\0" . 'EniBundle\\Entity\\Stagiaire' . "\0" . 'telephonefixe', '' . "\0" . 'EniBundle\\Entity\\Stagiaire' . "\0" . 'telephoneportable', '' . "\0" . 'EniBundle\\Entity\\Stagiaire' . "\0" . 'email', '' . "\0" . 'EniBundle\\Entity\\Stagiaire' . "\0" . 'datenaissance', '' . "\0" . 'EniBundle\\Entity\\Stagiaire' . "\0" . 'coderegion', '' . "\0" . 'EniBundle\\Entity\\Stagiaire' . "\0" . 'codenationalite', '' . "\0" . 'EniBundle\\Entity\\Stagiaire' . "\0" . 'codeoriginemedia', '' . "\0" . 'EniBundle\\Entity\\Stagiaire' . "\0" . 'datedernierenvoidoc', '' . "\0" . 'EniBundle\\Entity\\Stagiaire' . "\0" . 'datecreation', '' . "\0" . 'EniBundle\\Entity\\Stagiaire' . "\0" . 'repertoire', '' . "\0" . 'EniBundle\\Entity\\Stagiaire' . "\0" . 'permis', '' . "\0" . 'EniBundle\\Entity\\Stagiaire' . "\0" . 'photo', '' . "\0" . 'EniBundle\\Entity\\Stagiaire' . "\0" . 'envoidocencours', '' . "\0" . 'EniBundle\\Entity\\Stagiaire' . "\0" . 'historique', '' . "\0" . 'EniBundle\\Entity\\Stagiaire' . "\0" . 'codestagiaire'];
        }

        return ['__isInitialized__', '' . "\0" . 'EniBundle\\Entity\\Stagiaire' . "\0" . 'civilite', '' . "\0" . 'EniBundle\\Entity\\Stagiaire' . "\0" . 'nom', '' . "\0" . 'EniBundle\\Entity\\Stagiaire' . "\0" . 'prenom', '' . "\0" . 'EniBundle\\Entity\\Stagiaire' . "\0" . 'adresse1', '' . "\0" . 'EniBundle\\Entity\\Stagiaire' . "\0" . 'adresse2', '' . "\0" . 'EniBundle\\Entity\\Stagiaire' . "\0" . 'adresse3', '' . "\0" . 'EniBundle\\Entity\\Stagiaire' . "\0" . 'codepostal', '' . "\0" . 'EniBundle\\Entity\\Stagiaire' . "\0" . 'ville', '' . "\0" . 'EniBundle\\Entity\\Stagiaire' . "\0" . 'telephonefixe', '' . "\0" . 'EniBundle\\Entity\\Stagiaire' . "\0" . 'telephoneportable', '' . "\0" . 'EniBundle\\Entity\\Stagiaire' . "\0" . 'email', '' . "\0" . 'EniBundle\\Entity\\Stagiaire' . "\0" . 'datenaissance', '' . "\0" . 'EniBundle\\Entity\\Stagiaire' . "\0" . 'coderegion', '' . "\0" . 'EniBundle\\Entity\\Stagiaire' . "\0" . 'codenationalite', '' . "\0" . 'EniBundle\\Entity\\Stagiaire' . "\0" . 'codeoriginemedia', '' . "\0" . 'EniBundle\\Entity\\Stagiaire' . "\0" . 'datedernierenvoidoc', '' . "\0" . 'EniBundle\\Entity\\Stagiaire' . "\0" . 'datecreation', '' . "\0" . 'EniBundle\\Entity\\Stagiaire' . "\0" . 'repertoire', '' . "\0" . 'EniBundle\\Entity\\Stagiaire' . "\0" . 'permis', '' . "\0" . 'EniBundle\\Entity\\Stagiaire' . "\0" . 'photo', '' . "\0" . 'EniBundle\\Entity\\Stagiaire' . "\0" . 'envoidocencours', '' . "\0" . 'EniBundle\\Entity\\Stagiaire' . "\0" . 'historique', '' . "\0" . 'EniBundle\\Entity\\Stagiaire' . "\0" . 'codestagiaire'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Stagiaire $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function setCivilite($civilite)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCivilite', [$civilite]);

        return parent::setCivilite($civilite);
    }

    /**
     * {@inheritDoc}
     */
    public function getCivilite()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCivilite', []);

        return parent::getCivilite();
    }

    /**
     * {@inheritDoc}
     */
    public function setNom($nom)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNom', [$nom]);

        return parent::setNom($nom);
    }

    /**
     * {@inheritDoc}
     */
    public function getNom()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNom', []);

        return parent::getNom();
    }

    /**
     * {@inheritDoc}
     */
    public function setPrenom($prenom)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPrenom', [$prenom]);

        return parent::setPrenom($prenom);
    }

    /**
     * {@inheritDoc}
     */
    public function getPrenom()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPrenom', []);

        return parent::getPrenom();
    }

    /**
     * {@inheritDoc}
     */
    public function setAdresse1($adresse1)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAdresse1', [$adresse1]);

        return parent::setAdresse1($adresse1);
    }

    /**
     * {@inheritDoc}
     */
    public function getAdresse1()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAdresse1', []);

        return parent::getAdresse1();
    }

    /**
     * {@inheritDoc}
     */
    public function setAdresse2($adresse2)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAdresse2', [$adresse2]);

        return parent::setAdresse2($adresse2);
    }

    /**
     * {@inheritDoc}
     */
    public function getAdresse2()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAdresse2', []);

        return parent::getAdresse2();
    }

    /**
     * {@inheritDoc}
     */
    public function setAdresse3($adresse3)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAdresse3', [$adresse3]);

        return parent::setAdresse3($adresse3);
    }

    /**
     * {@inheritDoc}
     */
    public function getAdresse3()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAdresse3', []);

        return parent::getAdresse3();
    }

    /**
     * {@inheritDoc}
     */
    public function setCodepostal($codepostal)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCodepostal', [$codepostal]);

        return parent::setCodepostal($codepostal);
    }

    /**
     * {@inheritDoc}
     */
    public function getCodepostal()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCodepostal', []);

        return parent::getCodepostal();
    }

    /**
     * {@inheritDoc}
     */
    public function setVille($ville)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setVille', [$ville]);

        return parent::setVille($ville);
    }

    /**
     * {@inheritDoc}
     */
    public function getVille()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getVille', []);

        return parent::getVille();
    }

    /**
     * {@inheritDoc}
     */
    public function setTelephonefixe($telephonefixe)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTelephonefixe', [$telephonefixe]);

        return parent::setTelephonefixe($telephonefixe);
    }

    /**
     * {@inheritDoc}
     */
    public function getTelephonefixe()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTelephonefixe', []);

        return parent::getTelephonefixe();
    }

    /**
     * {@inheritDoc}
     */
    public function setTelephoneportable($telephoneportable)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTelephoneportable', [$telephoneportable]);

        return parent::setTelephoneportable($telephoneportable);
    }

    /**
     * {@inheritDoc}
     */
    public function getTelephoneportable()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTelephoneportable', []);

        return parent::getTelephoneportable();
    }

    /**
     * {@inheritDoc}
     */
    public function setEmail($email)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEmail', [$email]);

        return parent::setEmail($email);
    }

    /**
     * {@inheritDoc}
     */
    public function getEmail()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEmail', []);

        return parent::getEmail();
    }

    /**
     * {@inheritDoc}
     */
    public function setDatenaissance($datenaissance)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDatenaissance', [$datenaissance]);

        return parent::setDatenaissance($datenaissance);
    }

    /**
     * {@inheritDoc}
     */
    public function getDatenaissance()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDatenaissance', []);

        return parent::getDatenaissance();
    }

    /**
     * {@inheritDoc}
     */
    public function setCoderegion($coderegion)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCoderegion', [$coderegion]);

        return parent::setCoderegion($coderegion);
    }

    /**
     * {@inheritDoc}
     */
    public function getCoderegion()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCoderegion', []);

        return parent::getCoderegion();
    }

    /**
     * {@inheritDoc}
     */
    public function setCodenationalite($codenationalite)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCodenationalite', [$codenationalite]);

        return parent::setCodenationalite($codenationalite);
    }

    /**
     * {@inheritDoc}
     */
    public function getCodenationalite()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCodenationalite', []);

        return parent::getCodenationalite();
    }

    /**
     * {@inheritDoc}
     */
    public function setCodeoriginemedia($codeoriginemedia)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCodeoriginemedia', [$codeoriginemedia]);

        return parent::setCodeoriginemedia($codeoriginemedia);
    }

    /**
     * {@inheritDoc}
     */
    public function getCodeoriginemedia()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCodeoriginemedia', []);

        return parent::getCodeoriginemedia();
    }

    /**
     * {@inheritDoc}
     */
    public function setDatedernierenvoidoc($datedernierenvoidoc)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDatedernierenvoidoc', [$datedernierenvoidoc]);

        return parent::setDatedernierenvoidoc($datedernierenvoidoc);
    }

    /**
     * {@inheritDoc}
     */
    public function getDatedernierenvoidoc()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDatedernierenvoidoc', []);

        return parent::getDatedernierenvoidoc();
    }

    /**
     * {@inheritDoc}
     */
    public function setDatecreation($datecreation)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDatecreation', [$datecreation]);

        return parent::setDatecreation($datecreation);
    }

    /**
     * {@inheritDoc}
     */
    public function getDatecreation()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDatecreation', []);

        return parent::getDatecreation();
    }

    /**
     * {@inheritDoc}
     */
    public function setRepertoire($repertoire)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRepertoire', [$repertoire]);

        return parent::setRepertoire($repertoire);
    }

    /**
     * {@inheritDoc}
     */
    public function getRepertoire()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRepertoire', []);

        return parent::getRepertoire();
    }

    /**
     * {@inheritDoc}
     */
    public function setPermis($permis)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPermis', [$permis]);

        return parent::setPermis($permis);
    }

    /**
     * {@inheritDoc}
     */
    public function getPermis()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPermis', []);

        return parent::getPermis();
    }

    /**
     * {@inheritDoc}
     */
    public function setPhoto($photo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPhoto', [$photo]);

        return parent::setPhoto($photo);
    }

    /**
     * {@inheritDoc}
     */
    public function getPhoto()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPhoto', []);

        return parent::getPhoto();
    }

    /**
     * {@inheritDoc}
     */
    public function setEnvoidocencours($envoidocencours)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEnvoidocencours', [$envoidocencours]);

        return parent::setEnvoidocencours($envoidocencours);
    }

    /**
     * {@inheritDoc}
     */
    public function getEnvoidocencours()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEnvoidocencours', []);

        return parent::getEnvoidocencours();
    }

    /**
     * {@inheritDoc}
     */
    public function setHistorique($historique)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setHistorique', [$historique]);

        return parent::setHistorique($historique);
    }

    /**
     * {@inheritDoc}
     */
    public function getHistorique()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getHistorique', []);

        return parent::getHistorique();
    }

    /**
     * {@inheritDoc}
     */
    public function getCodestagiaire()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getCodestagiaire();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCodestagiaire', []);

        return parent::getCodestagiaire();
    }

}
